var mirageGuide = '<div class="guide-header"><div class="guide-header-meta"><span class="badge badge-cs2">CS2 Guide</span><span class="meta-item">8 \u043e\u043a\u0442 2024</span><span class="meta-item">1,630 просмотров</span><span class="meta-item gold">★★★★☆</span></div><h1>Гайд по карте «Мираж» в CS 2</h1><div class="author">by <strong>Чекунец</strong></div></div><div class="guide-body">'
  + '<p>Карта «Мираж» — это одна из самых популярных и стратегически сложных карт в Counter-Strike 2. В этом гайде мы рассмотрим ключевые позиции, стратегии для обеих сторон и советы для улучшения вашей игры.</p>'
  + '<img class="guide-cover" src="https://images.steamusercontent.com/ugc/2466374324921228776/269BBE8DACB19F91C834309DBD3C649CD9F79FE6/" alt="Mirage" loading="lazy">'
  + '<h3>Основная информация о карте</h3>'
  + '<p>Стороны: Террористы (Т) и Контр-террористы (КТ). Цели: Террористы должны установить бомбу на одной из точек (A или B), а КТ — предотвратить это или обезвредить бомбу.</p>'
  + '<h4>Балансировка</h4><p>«Мираж» известен своей сбалансированной конструкцией, что позволяет обеим сторонам проявлять стратегию и тактику.</p>'
  + '<h4>Разнообразие тактик</h4><p>Игроки могут применять различные подходы: от агрессивного контроля мида до осторожной установки бомбы.</p>'
  + '<h4>Использование гранат</h4><p>Грамотное использование дымов, флешек и молотов может существенно изменить ход раунда.</p>'
  + '<div class="guide-gallery"><img src="https://images.steamusercontent.com/ugc/2466374324921114483/F7C47C230EACAB2D33B4F2E3BE82AB70B0D6553B/" alt="Map" loading="lazy"></div>'
  + '<h3>Основные позиции</h3><h4>Т-сторона (T)</h4>'
  + '<ul><li><strong>T-спаун</strong> — начальная точка для террористов</li><li><strong>Мид</strong> — центральная зона, ключевая для контроля карты</li></ul>'
  + '<div class="guide-gallery"><img src="https://images.steamusercontent.com/ugc/2466374324921118512/36D6F40183CAA539464542C1B9AF9B3634B85993/" alt="T-side" loading="lazy"></div>'
  + '<h3>A-плэнт</h3><p>Основная зона для установки бомбы.</p>'
  + '<ul><li><strong>Яма</strong> — угол, откуда можно контролировать плент</li><li><strong>Тетрис</strong> — высокая позиция для снайперов</li><li><strong>Ковры</strong> — позиция для защиты и атаки</li></ul>'
  + '<h4>CT-сторона (CT)</h4>'
  + '<ul><li><strong>CT-спаун</strong> — начальная точка для контртеррористов</li><li><strong>A-сайт</strong> — защита A-плента</li><li><strong>Искра</strong> — высокая позиция для укрытия</li><li><strong>Default</strong> — позиция для защиты A</li></ul>'
  + '<div class="guide-gallery"><img src="https://images.steamusercontent.com/ugc/2466374324921119139/73B04908C31D4986F4052488EB89041722F62BDB/" alt="A site" loading="lazy"></div>'
  + '<h3>B-плэнт</h3><p>Вторая зона для установки бомбы.</p>'
  + '<ul><li><strong>Под окном</strong> — скрытая позиция для засады</li><li><strong>Лавка</strong> — удобное укрытие на B</li><li><strong>B-сайт</strong> — защита B-плента</li><li><strong>Under</strong> — вход на B через Apartments</li></ul>'
  + '<div class="guide-gallery"><img src="https://images.steamusercontent.com/ugc/2466374324921118521/6853FBEDD31C9F613CFB5F64A46DCB9CBA835FCA/" alt="B site" loading="lazy"><img src="https://images.steamusercontent.com/ugc/2466374324921115070/7CBDB73C2BA88CD1BCD083D72BFBE878A2351147/" alt="B under" loading="lazy"></div>'
  + '<h3>Тактики</h3><h4>Для Т-стороны</h4>'
  + '<p><strong>Контроль мида:</strong> занять мид двумя игроками, использовать дымы на окно и Connector.</p>'
  + '<p><strong>Атака на A:</strong> флешки для отвлечения, дымы на CT и Тикет.</p>'
  + '<p><strong>Атака на B:</strong> через Apps с дымами для защиты входа.</p>'
  + '<h4>Для CT-стороны</h4>'
  + '<p><strong>Контроль мида:</strong> один на окне, второй на Connector.</p>'
  + '<p><strong>Защита A:</strong> один на CT, второй на Тикет, третий на Default.</p>'
  + '<p><strong>Защита B:</strong> один на B-сайте, другой под окном.</p>'
  + '<h3>Общие советы</h3>'
  + '<ul><li><strong>Коммуникация</strong> — обсуждайте позиции с командой</li><li><strong>Экономика</strong> — следите за деньгами и планируйте эко-раунды</li><li><strong>Адаптация</strong> — меняйте стратегию под противника</li></ul>'
  + '<div class="guide-back"><a class="back-to-guides">← Назад к списку гайдов</a></div></div>';
